export enum CommunityType {
  Educational = 'educational',
  Athlete = 'athlete',
  Gaming = 'gaming',
  Hobby = 'hobby',
  Local = 'local',
  Creator = 'creator',
  Wellness = 'wellness',
  Financial = 'financial',
  Artistic = 'artistic',
  Technology = 'technology',
  Environmental = 'environmental',
  Scientific = 'scientific',
  Social = 'social',
  Culinary = 'culinary',
  Travel = 'travel',
  Entertainment = 'entertainment',
  Other = 'other',
}
